export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_FAIL = 'REGISTER_fAIL';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FAIL = 'LOGIN_fAIL';

export const LOGOUT = 'LOGOUT';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';


export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAIL = 'GET_COURSE_FAIL';

export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAIL = 'ADD_COURSE_FAIL';

export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL';


export const GET_CATEGORIE_SUCCESS = 'GET_CATEGORIE_SUCCESS';
export const GET_CATEGORIE_FAIL = 'GET_CATEGORIE_FAIL';

export const ADD_CATEGORIE_SUCCESS = 'ADD_CATEGORIE_SUCCESS';
export const ADD_CATEGORIE_FAIL = 'ADD_CATEGORIE_FAIL';

export const DELETE_CATEGORIE_SUCCESS = 'DELETE_CATEGORIE_SUCCESS';
export const DELETE_CATEGORIE_FAIL = 'DELETE_CATEGORIE_FAIL';